-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 19:59:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema notedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notedb` DEFAULT CHARACTER SET utf8 ;
USE `notedb` ;

-- -----------------------------------------------------
-- Table `notedb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notedb`.`roles` (
  `roleid` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`roleid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `notedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notedb`.`users` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `password` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `surname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `isblocked` TINYINT(1) NULL DEFAULT NULL,
  `roles_roleid` INT(11) NOT NULL,
  PRIMARY KEY (`userid`),
  INDEX `fk_users_roles_idx` (`roles_roleid` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_roleid`)
    REFERENCES `notedb`.`roles` (`roleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `notedb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notedb`.`status` (
  `statusid` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`statusid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `notedb`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notedb`.`note` (
  `noteid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `description` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `readed` TINYINT(1) NULL DEFAULT NULL,
  `status_statusid` INT(11) NOT NULL,
  `users_reporterId` INT(11) NOT NULL,
  `users_assigneeId` INT(11) NOT NULL,
  PRIMARY KEY (`noteid`),
  INDEX `fk_note_status1_idx` (`status_statusid` ASC),
  INDEX `fk_note_reporterId_idx` (`users_reporterId` ASC),
  INDEX `fk_note_assigneeId_idx` (`users_assigneeId` ASC),
  CONSTRAINT `fk_note_assigneeId`
    FOREIGN KEY (`users_assigneeId`)
    REFERENCES `notedb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_reporterId`
    FOREIGN KEY (`users_reporterId`)
    REFERENCES `notedb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_status1`
    FOREIGN KEY (`status_statusid`)
    REFERENCES `notedb`.`status` (`statusid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
